name: Setup Node.js and install NPM dependencies
description: Install Node.js and NPM, then install NPM dependencies

inputs:
  node-version:
    description: 'Which version of Node.js to install'
    required: false
    default: 'lts/*'
  registry-url:
    description: 'Which NPM registry url to use'
    required: false
    default: 'https://registry.npmjs.org'

runs:
  using: composite
  steps:
    - name: Setup Node.js and NPM
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Install NPM dependencies
      shell: bash
      run: npm ci
