name: 'E2E Demo'
on:
  push:
    branches: [stable, develop]
  pull_request:
    branches: [develop]
jobs:
  test:
    name: Run E2E tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Read .nvmrc
        id: nvm
        run: echo "##[set-output name=NODE_VERSION;]$(cat .nvmrc)"
      - name: Setup node.js
        uses: actions/setup-node@v3.2.0
        with:
          node-version: '${{ steps.nvm.outputs.NODE_VERSION }}'
      - name: Get yarn cache directory path
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore dependencies cache
        uses: actions/cache@v2.1.5
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-
      - name: Install dependencies
        run: yarn install --frozen-lockfile --silent
      - name: Build library
        run: yarn run build:lib
      - name: Build demo app
        run: yarn run build:demo
      - name: Run cypress
        uses: cypress-io/github-action@v2
        with:
          start: yarn run serve -l 4200 ./dist/demo
          wait-on: 'http://localhost:4200'
          project: projects/demo-e2e
          browser: chrome
          headless: true
      - name: Upload videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: demo-e2e-videos
          path: dist/cypress/demo/videos
      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: demo-e2e-screenshots
          path: dist/cypress/demo/screenshots
