name: Main
on:
  push:
    branches: [stable, develop]
  pull_request:
    branches: [develop]
jobs:
  build:
    name: Run build and unit tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Read .nvmrc
        id: nvm
        run: echo "##[set-output name=NODE_VERSION;]$(cat .nvmrc)"
      - name: Setup node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '${{ steps.nvm.outputs.NODE_VERSION }}'
      - name: Get yarn cache directory path
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore dependencies cache
        uses: actions/cache@v2.1.5
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-
      - name: Install dependencies
        run: yarn install --frozen-lockfile --silent
      - name: Check code format
        run: yarn run format:check
      - name: Lint
        run: |
          yarn run lint:demo
          yarn run lint:demo-e2e
          yarn run lint:example
          yarn run lint:lib
      - name: Build
        run: |
          yarn run build:lib
          yarn run build:demo --progress=false
          yarn run build:example --progress=false
      - name: Upload library build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ng-in-viewport
          path: dist/ng-in-viewport
      - name: Upload demo build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ng-in-viewport-demo
          path: dist/demo
      - name: Upload example build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ng-in-viewport-example
          path: dist/example
      # - name: Test
      #   run: yarn run test --ci --coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v1.5.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: coverage/all/lcov.info
