name: qodana-scan

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [develop]
  push:
    branches: [stable, develop]
  workflow_dispatch:
    inputs:
      reason:
        description: Why was the workflow triggered manually?
        required: true
        type: string

permissions:
  contents: read

jobs:
  qodana:
    name: Run code quality monitoring
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js and install NPM dependencies
        uses: ./.github/actions/install-npm-deps

      - name: Qodana Scan
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        uses: JetBrains/qodana-action@v2023.1.5
        with:
          args: --baseline,qodana.sarif.json
          cache-default-branch-only: true
