name: qodana-scan

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  qodana:
    name: Run code quality monitoring
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js and install NPM dependencies
        uses: ./.github/actions/install-npm-deps
        with:
          npm-cache-key: 'npm-cache-qodana'

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2022.3.4
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
