name: release-please

on:
  push:
    branches: [develop]
  workflow_dispatch:
    inputs:
      reason:
        description: Why was the workflow triggered manually?
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare release PR or move on with release when PR was accepted
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          package-name: ng-in-viewport
          extra-files: |
            README.md
            projects/ng-in-viewport/package.json

      - name: Checkout repository
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v3

      - name: Setup Node.js and install NPM dependencies
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/install-npm-deps
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Build library
        if: ${{ steps.release.outputs.release_created }}
        run: npm run build:lib

      - name: Copy license and readme files
        if: ${{ steps.release.outputs.release_created }}
        run: |
          cp LICENSE dist/ng-in-viewport/LICENSE
          cp README.md dist/ng-in-viewport/README.md

      - name: Publish library package
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd dist/ng-in-viewport
          npm publish --provenance --access public
